/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RendaPassivaRouteImport } from './routes/renda-passiva'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PatrimonioRouteImport } from './routes/patrimonio'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as IaRouteImport } from './routes/ia'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as EducacaoRouteImport } from './routes/educacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatrimonioIndexRouteImport } from './routes/patrimonio.index'
import { Route as PatrimonioCofreRouteImport } from './routes/patrimonio.cofre'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const RendaPassivaRoute = RendaPassivaRouteImport.update({
  id: '/renda-passiva',
  path: '/renda-passiva',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioRoute = PatrimonioRouteImport.update({
  id: '/patrimonio',
  path: '/patrimonio',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacaoRoute = EducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrimonioIndexRoute = PatrimonioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatrimonioRoute,
} as any)
const PatrimonioCofreRoute = PatrimonioCofreRouteImport.update({
  id: '/cofre',
  path: '/cofre',
  getParentRoute: () => PatrimonioRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/educacao': typeof EducacaoRoute
  '/financas': typeof FinancasRoute
  '/ia': typeof IaRoute
  '/noticias': typeof NoticiasRoute
  '/patrimonio': typeof PatrimonioRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/renda-passiva': typeof RendaPassivaRoute
  '/api/chat': typeof ApiChatRoute
  '/patrimonio/cofre': typeof PatrimonioCofreRoute
  '/patrimonio/': typeof PatrimonioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/educacao': typeof EducacaoRoute
  '/financas': typeof FinancasRoute
  '/ia': typeof IaRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/renda-passiva': typeof RendaPassivaRoute
  '/api/chat': typeof ApiChatRoute
  '/patrimonio/cofre': typeof PatrimonioCofreRoute
  '/patrimonio': typeof PatrimonioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/educacao': typeof EducacaoRoute
  '/financas': typeof FinancasRoute
  '/ia': typeof IaRoute
  '/noticias': typeof NoticiasRoute
  '/patrimonio': typeof PatrimonioRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/renda-passiva': typeof RendaPassivaRoute
  '/api/chat': typeof ApiChatRoute
  '/patrimonio/cofre': typeof PatrimonioCofreRoute
  '/patrimonio/': typeof PatrimonioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/educacao'
    | '/financas'
    | '/ia'
    | '/noticias'
    | '/patrimonio'
    | '/perfil'
    | '/renda-passiva'
    | '/api/chat'
    | '/patrimonio/cofre'
    | '/patrimonio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/educacao'
    | '/financas'
    | '/ia'
    | '/noticias'
    | '/perfil'
    | '/renda-passiva'
    | '/api/chat'
    | '/patrimonio/cofre'
    | '/patrimonio'
  id:
    | '__root__'
    | '/'
    | '/educacao'
    | '/financas'
    | '/ia'
    | '/noticias'
    | '/patrimonio'
    | '/perfil'
    | '/renda-passiva'
    | '/api/chat'
    | '/patrimonio/cofre'
    | '/patrimonio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EducacaoRoute: typeof EducacaoRoute
  FinancasRoute: typeof FinancasRoute
  IaRoute: typeof IaRoute
  NoticiasRoute: typeof NoticiasRoute
  PatrimonioRoute: typeof PatrimonioRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  RendaPassivaRoute: typeof RendaPassivaRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renda-passiva': {
      id: '/renda-passiva'
      path: '/renda-passiva'
      fullPath: '/renda-passiva'
      preLoaderRoute: typeof RendaPassivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio': {
      id: '/patrimonio'
      path: '/patrimonio'
      fullPath: '/patrimonio'
      preLoaderRoute: typeof PatrimonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacao': {
      id: '/educacao'
      path: '/educacao'
      fullPath: '/educacao'
      preLoaderRoute: typeof EducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrimonio/': {
      id: '/patrimonio/'
      path: '/'
      fullPath: '/patrimonio/'
      preLoaderRoute: typeof PatrimonioIndexRouteImport
      parentRoute: typeof PatrimonioRoute
    }
    '/patrimonio/cofre': {
      id: '/patrimonio/cofre'
      path: '/cofre'
      fullPath: '/patrimonio/cofre'
      preLoaderRoute: typeof PatrimonioCofreRouteImport
      parentRoute: typeof PatrimonioRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PatrimonioRouteChildren {
  PatrimonioCofreRoute: typeof PatrimonioCofreRoute
  PatrimonioIndexRoute: typeof PatrimonioIndexRoute
}

const PatrimonioRouteChildren: PatrimonioRouteChildren = {
  PatrimonioCofreRoute: PatrimonioCofreRoute,
  PatrimonioIndexRoute: PatrimonioIndexRoute,
}

const PatrimonioRouteWithChildren = PatrimonioRoute._addFileChildren(
  PatrimonioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EducacaoRoute: EducacaoRoute,
  FinancasRoute: FinancasRoute,
  IaRoute: IaRoute,
  NoticiasRoute: NoticiasRoute,
  PatrimonioRoute: PatrimonioRouteWithChildren,
  PerfilRoute: PerfilRoute,
  RendaPassivaRoute: RendaPassivaRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
